import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './global.css';
import Providers from './providers';
import URLBar from './url-bar';
import { Suspense } from 'react';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white text-gray-900 antialiased flex flex-col h-full group`}
      >
        <Providers>
          <div className="group-has-[[data-hide-urlbar]]:hidden">
            <URLBar />
          </div>

          <main className="h-full flex flex-col p-4 sm:py-4 sm:px-6 overflow-y-scroll">
            <Suspense>{children}</Suspense>
          </main>
        </Providers>
      </body>
    </html>
  );
}
